<?php


/**
 * This class defines the structure of the 'sf_tagging' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:59 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.sfPropelActAsTaggableBehaviorPlugin.lib.model.map
 */
class TaggingTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.sfPropelActAsTaggableBehaviorPlugin.lib.model.map.TaggingTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sf_tagging');
		$this->setPhpName('Tagging');
		$this->setClassname('Tagging');
		$this->setPackage('plugins.sfPropelActAsTaggableBehaviorPlugin.lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('sf_tagging_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'ID', 'INTEGER', true, null, null);
		$this->addForeignKey('TAG_ID', 'TagId', 'INTEGER', 'sf_tag', 'ID', true, null, null);
		$this->addColumn('TAGGABLE_MODEL', 'TaggableModel', 'VARCHAR', false, 30, null);
		$this->addColumn('TAGGABLE_ID', 'TaggableId', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Tag', 'Tag', RelationMap::MANY_TO_ONE, array('tag_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // TaggingTableMap
