<?php


/**
 * This class defines the structure of the 'activities' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:58 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ActivityTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ActivityTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('activities');
		$this->setPhpName('Activity');
		$this->setClassname('Activity');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('activities_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NAME_PT', 'NamePt', 'LONGVARCHAR', false, null, null);
		$this->addColumn('NAME_US', 'NameUs', 'LONGVARCHAR', false, null, null);
		$this->addColumn('FRAMEWORK_NAME', 'FrameworkName', 'LONGVARCHAR', false, null, null);
		$this->addForeignKey('ACTIVITY_PARENT', 'ActivityParent', 'INTEGER', 'activities', 'ID', false, null, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null, null);
		$this->addForeignKey('FRAMEWORK_ID', 'FrameworkId', 'INTEGER', 'frameworks', 'ID', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ActivityRelatedByActivityParent', 'Activity', RelationMap::MANY_TO_ONE, array('activity_parent' => 'id', ), null, null);
    $this->addRelation('Framework', 'Framework', RelationMap::MANY_TO_ONE, array('framework_id' => 'id', ), null, null);
    $this->addRelation('ActivityRelatedByActivityParent', 'Activity', RelationMap::ONE_TO_MANY, array('id' => 'activity_parent', ), null, null);
    $this->addRelation('Job', 'Job', RelationMap::ONE_TO_MANY, array('id' => 'activity_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ActivityTableMap
