<?php


/**
 * This class defines the structure of the 'rsl_results' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:58 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RslResultTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RslResultTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('rsl_results');
		$this->setPhpName('RslResult');
		$this->setClassname('RslResult');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('rsl_results_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('DATA_SINTESYS', 'DataSintesys', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CLASS_DESCRIPTION', 'ClassDescription', 'LONGVARCHAR', false, null, null);
		$this->addColumn('META_SINTESYS', 'MetaSintesys', 'LONGVARCHAR', false, null, null);
		$this->addColumn('RESULTS', 'Results', 'LONGVARCHAR', false, null, null);
		$this->addColumn('DISCUSSIONS', 'Discussions', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CONCLUSIONS', 'Conclusions', 'LONGVARCHAR', false, null, null);
		$this->addColumn('PRACTICE_IMPLICATIONS', 'PracticeImplications', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SEARCH_IMPLICATIONS', 'SearchImplications', 'LONGVARCHAR', false, null, null);
		$this->addColumn('APPOINTMENTS', 'Appointments', 'LONGVARCHAR', false, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('DELETED_AT', 'DeletedAt', 'TIMESTAMP', false, null, null);
		$this->addForeignKey('CREATED_BY', 'CreatedBy', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('UPDATED_BY', 'UpdatedBy', 'INTEGER', 'sf_guard_user', 'ID', true, null, null);
		$this->addForeignKey('DELETED_BY', 'DeletedBy', 'INTEGER', 'sf_guard_user', 'ID', false, null, null);
		$this->addForeignKey('RSL_ID', 'RslId', 'INTEGER', 'systematic_reviews', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('sfGuardUserRelatedByCreatedBy', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('created_by' => 'id', ), 'CASCADE', null);
    $this->addRelation('sfGuardUserRelatedByUpdatedBy', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('updated_by' => 'id', ), 'CASCADE', null);
    $this->addRelation('sfGuardUserRelatedByDeletedBy', 'sfGuardUser', RelationMap::MANY_TO_ONE, array('deleted_by' => 'id', ), 'CASCADE', null);
    $this->addRelation('SystematicReview', 'SystematicReview', RelationMap::MANY_TO_ONE, array('rsl_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // RslResultTableMap
