<?php


/**
 * This class defines the structure of the 'systematic_reviews_search_bases' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:58 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SystematicReviewSearchBaseTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SystematicReviewSearchBaseTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('systematic_reviews_search_bases');
		$this->setPhpName('SystematicReviewSearchBase');
		$this->setClassname('SystematicReviewSearchBase');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('systematic_reviews_search_bases_id_seq');
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('SYSTEMATIC_REVIEW_ID', 'SystematicReviewId', 'INTEGER', 'systematic_reviews', 'ID', true, null, null);
		$this->addForeignKey('SEARCH_BASE_ID', 'SearchBaseId', 'INTEGER', 'search_bases', 'ID', true, null, null);
		$this->addForeignKey('PROTOCOL_ID', 'ProtocolId', 'INTEGER', 'protocols', 'ID', true, null, null);
		$this->addColumn('QUERY_STRING', 'QueryString', 'LONGVARCHAR', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('SystematicReview', 'SystematicReview', RelationMap::MANY_TO_ONE, array('systematic_review_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('SearchBase', 'SearchBase', RelationMap::MANY_TO_ONE, array('search_base_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Protocol', 'Protocol', RelationMap::MANY_TO_ONE, array('protocol_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SystematicReviewSearchBaseTableMap
