<?php

/**
 * Base class that represents a row from the 'activities' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:58 2013
 *
 * @package    lib.model.om
 */
abstract class BaseActivity extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ActivityPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name_pt field.
	 * @var        string
	 */
	protected $name_pt;

	/**
	 * The value for the name_us field.
	 * @var        string
	 */
	protected $name_us;

	/**
	 * The value for the framework_name field.
	 * @var        string
	 */
	protected $framework_name;

	/**
	 * The value for the activity_parent field.
	 * @var        int
	 */
	protected $activity_parent;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the framework_id field.
	 * @var        int
	 */
	protected $framework_id;

	/**
	 * @var        Activity
	 */
	protected $aActivityRelatedByActivityParent;

	/**
	 * @var        Framework
	 */
	protected $aFramework;

	/**
	 * @var        array Activity[] Collection to store aggregation of Activity objects.
	 */
	protected $collActivitysRelatedByActivityParent;

	/**
	 * @var        Criteria The criteria used to select the current contents of collActivitysRelatedByActivityParent.
	 */
	private $lastActivityRelatedByActivityParentCriteria = null;

	/**
	 * @var        array Job[] Collection to store aggregation of Job objects.
	 */
	protected $collJobs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collJobs.
	 */
	private $lastJobCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ActivityPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name_pt] column value.
	 * 
	 * @return     string
	 */
	public function getNamePt()
	{
		return $this->name_pt;
	}

	/**
	 * Get the [name_us] column value.
	 * 
	 * @return     string
	 */
	public function getNameUs()
	{
		return $this->name_us;
	}

	/**
	 * Get the [framework_name] column value.
	 * 
	 * @return     string
	 */
	public function getFrameworkName()
	{
		return $this->framework_name;
	}

	/**
	 * Get the [activity_parent] column value.
	 * 
	 * @return     int
	 */
	public function getActivityParent()
	{
		return $this->activity_parent;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [framework_id] column value.
	 * 
	 * @return     int
	 */
	public function getFrameworkId()
	{
		return $this->framework_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ActivityPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name_pt] column.
	 * 
	 * @param      string $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setNamePt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name_pt !== $v) {
			$this->name_pt = $v;
			$this->modifiedColumns[] = ActivityPeer::NAME_PT;
		}

		return $this;
	} // setNamePt()

	/**
	 * Set the value of [name_us] column.
	 * 
	 * @param      string $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setNameUs($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name_us !== $v) {
			$this->name_us = $v;
			$this->modifiedColumns[] = ActivityPeer::NAME_US;
		}

		return $this;
	} // setNameUs()

	/**
	 * Set the value of [framework_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setFrameworkName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->framework_name !== $v) {
			$this->framework_name = $v;
			$this->modifiedColumns[] = ActivityPeer::FRAMEWORK_NAME;
		}

		return $this;
	} // setFrameworkName()

	/**
	 * Set the value of [activity_parent] column.
	 * 
	 * @param      int $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setActivityParent($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->activity_parent !== $v) {
			$this->activity_parent = $v;
			$this->modifiedColumns[] = ActivityPeer::ACTIVITY_PARENT;
		}

		if ($this->aActivityRelatedByActivityParent !== null && $this->aActivityRelatedByActivityParent->getId() !== $v) {
			$this->aActivityRelatedByActivityParent = null;
		}

		return $this;
	} // setActivityParent()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = ActivityPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [framework_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Activity The current object (for fluent API support)
	 */
	public function setFrameworkId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->framework_id !== $v) {
			$this->framework_id = $v;
			$this->modifiedColumns[] = ActivityPeer::FRAMEWORK_ID;
		}

		if ($this->aFramework !== null && $this->aFramework->getId() !== $v) {
			$this->aFramework = null;
		}

		return $this;
	} // setFrameworkId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name_pt = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->name_us = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->framework_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->activity_parent = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->description = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->framework_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = ActivityPeer::NUM_COLUMNS - ActivityPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Activity object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aActivityRelatedByActivityParent !== null && $this->activity_parent !== $this->aActivityRelatedByActivityParent->getId()) {
			$this->aActivityRelatedByActivityParent = null;
		}
		if ($this->aFramework !== null && $this->framework_id !== $this->aFramework->getId()) {
			$this->aFramework = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ActivityPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ActivityPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aActivityRelatedByActivityParent = null;
			$this->aFramework = null;
			$this->collActivitysRelatedByActivityParent = null;
			$this->lastActivityRelatedByActivityParentCriteria = null;

			$this->collJobs = null;
			$this->lastJobCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ActivityPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseActivity:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ActivityPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseActivity:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ActivityPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseActivity:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseActivity:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ActivityPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aActivityRelatedByActivityParent !== null) {
				if ($this->aActivityRelatedByActivityParent->isModified() || $this->aActivityRelatedByActivityParent->isNew()) {
					$affectedRows += $this->aActivityRelatedByActivityParent->save($con);
				}
				$this->setActivityRelatedByActivityParent($this->aActivityRelatedByActivityParent);
			}

			if ($this->aFramework !== null) {
				if ($this->aFramework->isModified() || $this->aFramework->isNew()) {
					$affectedRows += $this->aFramework->save($con);
				}
				$this->setFramework($this->aFramework);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ActivityPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ActivityPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ActivityPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collActivitysRelatedByActivityParent !== null) {
				foreach ($this->collActivitysRelatedByActivityParent as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collJobs !== null) {
				foreach ($this->collJobs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aActivityRelatedByActivityParent !== null) {
				if (!$this->aActivityRelatedByActivityParent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aActivityRelatedByActivityParent->getValidationFailures());
				}
			}

			if ($this->aFramework !== null) {
				if (!$this->aFramework->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFramework->getValidationFailures());
				}
			}


			if (($retval = ActivityPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collActivitysRelatedByActivityParent !== null) {
					foreach ($this->collActivitysRelatedByActivityParent as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collJobs !== null) {
					foreach ($this->collJobs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ActivityPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getNamePt();
				break;
			case 2:
				return $this->getNameUs();
				break;
			case 3:
				return $this->getFrameworkName();
				break;
			case 4:
				return $this->getActivityParent();
				break;
			case 5:
				return $this->getDescription();
				break;
			case 6:
				return $this->getFrameworkId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ActivityPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getNamePt(),
			$keys[2] => $this->getNameUs(),
			$keys[3] => $this->getFrameworkName(),
			$keys[4] => $this->getActivityParent(),
			$keys[5] => $this->getDescription(),
			$keys[6] => $this->getFrameworkId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ActivityPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setNamePt($value);
				break;
			case 2:
				$this->setNameUs($value);
				break;
			case 3:
				$this->setFrameworkName($value);
				break;
			case 4:
				$this->setActivityParent($value);
				break;
			case 5:
				$this->setDescription($value);
				break;
			case 6:
				$this->setFrameworkId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ActivityPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNamePt($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNameUs($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFrameworkName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setActivityParent($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDescription($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFrameworkId($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ActivityPeer::DATABASE_NAME);

		if ($this->isColumnModified(ActivityPeer::ID)) $criteria->add(ActivityPeer::ID, $this->id);
		if ($this->isColumnModified(ActivityPeer::NAME_PT)) $criteria->add(ActivityPeer::NAME_PT, $this->name_pt);
		if ($this->isColumnModified(ActivityPeer::NAME_US)) $criteria->add(ActivityPeer::NAME_US, $this->name_us);
		if ($this->isColumnModified(ActivityPeer::FRAMEWORK_NAME)) $criteria->add(ActivityPeer::FRAMEWORK_NAME, $this->framework_name);
		if ($this->isColumnModified(ActivityPeer::ACTIVITY_PARENT)) $criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->activity_parent);
		if ($this->isColumnModified(ActivityPeer::DESCRIPTION)) $criteria->add(ActivityPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(ActivityPeer::FRAMEWORK_ID)) $criteria->add(ActivityPeer::FRAMEWORK_ID, $this->framework_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ActivityPeer::DATABASE_NAME);

		$criteria->add(ActivityPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Activity (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNamePt($this->name_pt);

		$copyObj->setNameUs($this->name_us);

		$copyObj->setFrameworkName($this->framework_name);

		$copyObj->setActivityParent($this->activity_parent);

		$copyObj->setDescription($this->description);

		$copyObj->setFrameworkId($this->framework_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getActivitysRelatedByActivityParent() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addActivityRelatedByActivityParent($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getJobs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addJob($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Activity Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ActivityPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ActivityPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Activity object.
	 *
	 * @param      Activity $v
	 * @return     Activity The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setActivityRelatedByActivityParent(Activity $v = null)
	{
		if ($v === null) {
			$this->setActivityParent(NULL);
		} else {
			$this->setActivityParent($v->getId());
		}

		$this->aActivityRelatedByActivityParent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Activity object, it will not be re-added.
		if ($v !== null) {
			$v->addActivityRelatedByActivityParent($this);
		}

		return $this;
	}


	/**
	 * Get the associated Activity object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Activity The associated Activity object.
	 * @throws     PropelException
	 */
	public function getActivityRelatedByActivityParent(PropelPDO $con = null)
	{
		if ($this->aActivityRelatedByActivityParent === null && ($this->activity_parent !== null)) {
			$this->aActivityRelatedByActivityParent = ActivityPeer::retrieveByPk($this->activity_parent);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aActivityRelatedByActivityParent->addActivitysRelatedByActivityParent($this);
			 */
		}
		return $this->aActivityRelatedByActivityParent;
	}

	/**
	 * Declares an association between this object and a Framework object.
	 *
	 * @param      Framework $v
	 * @return     Activity The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFramework(Framework $v = null)
	{
		if ($v === null) {
			$this->setFrameworkId(NULL);
		} else {
			$this->setFrameworkId($v->getId());
		}

		$this->aFramework = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Framework object, it will not be re-added.
		if ($v !== null) {
			$v->addActivity($this);
		}

		return $this;
	}


	/**
	 * Get the associated Framework object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Framework The associated Framework object.
	 * @throws     PropelException
	 */
	public function getFramework(PropelPDO $con = null)
	{
		if ($this->aFramework === null && ($this->framework_id !== null)) {
			$this->aFramework = FrameworkPeer::retrieveByPk($this->framework_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFramework->addActivitys($this);
			 */
		}
		return $this->aFramework;
	}

	/**
	 * Clears out the collActivitysRelatedByActivityParent collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addActivitysRelatedByActivityParent()
	 */
	public function clearActivitysRelatedByActivityParent()
	{
		$this->collActivitysRelatedByActivityParent = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collActivitysRelatedByActivityParent collection (array).
	 *
	 * By default this just sets the collActivitysRelatedByActivityParent collection to an empty array (like clearcollActivitysRelatedByActivityParent());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initActivitysRelatedByActivityParent()
	{
		$this->collActivitysRelatedByActivityParent = array();
	}

	/**
	 * Gets an array of Activity objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Activity has previously been saved, it will retrieve
	 * related ActivitysRelatedByActivityParent from storage. If this Activity is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Activity[]
	 * @throws     PropelException
	 */
	public function getActivitysRelatedByActivityParent($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActivitysRelatedByActivityParent === null) {
			if ($this->isNew()) {
			   $this->collActivitysRelatedByActivityParent = array();
			} else {

				$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

				ActivityPeer::addSelectColumns($criteria);
				$this->collActivitysRelatedByActivityParent = ActivityPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

				ActivityPeer::addSelectColumns($criteria);
				if (!isset($this->lastActivityRelatedByActivityParentCriteria) || !$this->lastActivityRelatedByActivityParentCriteria->equals($criteria)) {
					$this->collActivitysRelatedByActivityParent = ActivityPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastActivityRelatedByActivityParentCriteria = $criteria;
		return $this->collActivitysRelatedByActivityParent;
	}

	/**
	 * Returns the number of related Activity objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Activity objects.
	 * @throws     PropelException
	 */
	public function countActivitysRelatedByActivityParent(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collActivitysRelatedByActivityParent === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

				$count = ActivityPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

				if (!isset($this->lastActivityRelatedByActivityParentCriteria) || !$this->lastActivityRelatedByActivityParentCriteria->equals($criteria)) {
					$count = ActivityPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collActivitysRelatedByActivityParent);
				}
			} else {
				$count = count($this->collActivitysRelatedByActivityParent);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Activity object to this object
	 * through the Activity foreign key attribute.
	 *
	 * @param      Activity $l Activity
	 * @return     void
	 * @throws     PropelException
	 */
	public function addActivityRelatedByActivityParent(Activity $l)
	{
		if ($this->collActivitysRelatedByActivityParent === null) {
			$this->initActivitysRelatedByActivityParent();
		}
		if (!in_array($l, $this->collActivitysRelatedByActivityParent, true)) { // only add it if the **same** object is not already associated
			array_push($this->collActivitysRelatedByActivityParent, $l);
			$l->setActivityRelatedByActivityParent($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Activity is new, it will return
	 * an empty collection; or if this Activity has previously
	 * been saved, it will retrieve related ActivitysRelatedByActivityParent from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Activity.
	 */
	public function getActivitysRelatedByActivityParentJoinFramework($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collActivitysRelatedByActivityParent === null) {
			if ($this->isNew()) {
				$this->collActivitysRelatedByActivityParent = array();
			} else {

				$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

				$this->collActivitysRelatedByActivityParent = ActivityPeer::doSelectJoinFramework($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ActivityPeer::ACTIVITY_PARENT, $this->id);

			if (!isset($this->lastActivityRelatedByActivityParentCriteria) || !$this->lastActivityRelatedByActivityParentCriteria->equals($criteria)) {
				$this->collActivitysRelatedByActivityParent = ActivityPeer::doSelectJoinFramework($criteria, $con, $join_behavior);
			}
		}
		$this->lastActivityRelatedByActivityParentCriteria = $criteria;

		return $this->collActivitysRelatedByActivityParent;
	}

	/**
	 * Clears out the collJobs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addJobs()
	 */
	public function clearJobs()
	{
		$this->collJobs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collJobs collection (array).
	 *
	 * By default this just sets the collJobs collection to an empty array (like clearcollJobs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initJobs()
	{
		$this->collJobs = array();
	}

	/**
	 * Gets an array of Job objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Activity has previously been saved, it will retrieve
	 * related Jobs from storage. If this Activity is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Job[]
	 * @throws     PropelException
	 */
	public function getJobs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
			   $this->collJobs = array();
			} else {

				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				JobPeer::addSelectColumns($criteria);
				$this->collJobs = JobPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				JobPeer::addSelectColumns($criteria);
				if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
					$this->collJobs = JobPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastJobCriteria = $criteria;
		return $this->collJobs;
	}

	/**
	 * Returns the number of related Job objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Job objects.
	 * @throws     PropelException
	 */
	public function countJobs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				$count = JobPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
					$count = JobPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collJobs);
				}
			} else {
				$count = count($this->collJobs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Job object to this object
	 * through the Job foreign key attribute.
	 *
	 * @param      Job $l Job
	 * @return     void
	 * @throws     PropelException
	 */
	public function addJob(Job $l)
	{
		if ($this->collJobs === null) {
			$this->initJobs();
		}
		if (!in_array($l, $this->collJobs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collJobs, $l);
			$l->setActivity($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Activity is new, it will return
	 * an empty collection; or if this Activity has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Activity.
	 */
	public function getJobsJoinsfGuardUserRelatedByUserId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByUserId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByUserId($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Activity is new, it will return
	 * an empty collection; or if this Activity has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Activity.
	 */
	public function getJobsJoinProtocol($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinProtocol($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinProtocol($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Activity is new, it will return
	 * an empty collection; or if this Activity has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Activity.
	 */
	public function getJobsJoinsfGuardUserRelatedByFinishedBy($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ActivityPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByFinishedBy($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::ACTIVITY_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByFinishedBy($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collActivitysRelatedByActivityParent) {
				foreach ((array) $this->collActivitysRelatedByActivityParent as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collJobs) {
				foreach ((array) $this->collJobs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collActivitysRelatedByActivityParent = null;
		$this->collJobs = null;
			$this->aActivityRelatedByActivityParent = null;
			$this->aFramework = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseActivity:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseActivity::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseActivity
