<?php

/**
 * Base class that represents a row from the 'rsl_results' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:58 2013
 *
 * @package    lib.model.om
 */
abstract class BaseRslResult extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RslResultPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the data_sintesys field.
	 * @var        string
	 */
	protected $data_sintesys;

	/**
	 * The value for the class_description field.
	 * @var        string
	 */
	protected $class_description;

	/**
	 * The value for the meta_sintesys field.
	 * @var        string
	 */
	protected $meta_sintesys;

	/**
	 * The value for the results field.
	 * @var        string
	 */
	protected $results;

	/**
	 * The value for the discussions field.
	 * @var        string
	 */
	protected $discussions;

	/**
	 * The value for the conclusions field.
	 * @var        string
	 */
	protected $conclusions;

	/**
	 * The value for the practice_implications field.
	 * @var        string
	 */
	protected $practice_implications;

	/**
	 * The value for the search_implications field.
	 * @var        string
	 */
	protected $search_implications;

	/**
	 * The value for the appointments field.
	 * @var        string
	 */
	protected $appointments;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the created_by field.
	 * @var        int
	 */
	protected $created_by;

	/**
	 * The value for the updated_by field.
	 * @var        int
	 */
	protected $updated_by;

	/**
	 * The value for the deleted_by field.
	 * @var        int
	 */
	protected $deleted_by;

	/**
	 * The value for the rsl_id field.
	 * @var        int
	 */
	protected $rsl_id;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByCreatedBy;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByUpdatedBy;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByDeletedBy;

	/**
	 * @var        SystematicReview
	 */
	protected $aSystematicReview;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'RslResultPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [data_sintesys] column value.
	 * 
	 * @return     string
	 */
	public function getDataSintesys()
	{
		return $this->data_sintesys;
	}

	/**
	 * Get the [class_description] column value.
	 * 
	 * @return     string
	 */
	public function getClassDescription()
	{
		return $this->class_description;
	}

	/**
	 * Get the [meta_sintesys] column value.
	 * 
	 * @return     string
	 */
	public function getMetaSintesys()
	{
		return $this->meta_sintesys;
	}

	/**
	 * Get the [results] column value.
	 * 
	 * @return     string
	 */
	public function getResults()
	{
		return $this->results;
	}

	/**
	 * Get the [discussions] column value.
	 * 
	 * @return     string
	 */
	public function getDiscussions()
	{
		return $this->discussions;
	}

	/**
	 * Get the [conclusions] column value.
	 * 
	 * @return     string
	 */
	public function getConclusions()
	{
		return $this->conclusions;
	}

	/**
	 * Get the [practice_implications] column value.
	 * 
	 * @return     string
	 */
	public function getPracticeImplications()
	{
		return $this->practice_implications;
	}

	/**
	 * Get the [search_implications] column value.
	 * 
	 * @return     string
	 */
	public function getSearchImplications()
	{
		return $this->search_implications;
	}

	/**
	 * Get the [appointments] column value.
	 * 
	 * @return     string
	 */
	public function getAppointments()
	{
		return $this->appointments;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->deleted_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [created_by] column value.
	 * 
	 * @return     int
	 */
	public function getCreatedBy()
	{
		return $this->created_by;
	}

	/**
	 * Get the [updated_by] column value.
	 * 
	 * @return     int
	 */
	public function getUpdatedBy()
	{
		return $this->updated_by;
	}

	/**
	 * Get the [deleted_by] column value.
	 * 
	 * @return     int
	 */
	public function getDeletedBy()
	{
		return $this->deleted_by;
	}

	/**
	 * Get the [rsl_id] column value.
	 * 
	 * @return     int
	 */
	public function getRslId()
	{
		return $this->rsl_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RslResultPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [data_sintesys] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setDataSintesys($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->data_sintesys !== $v) {
			$this->data_sintesys = $v;
			$this->modifiedColumns[] = RslResultPeer::DATA_SINTESYS;
		}

		return $this;
	} // setDataSintesys()

	/**
	 * Set the value of [class_description] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setClassDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->class_description !== $v) {
			$this->class_description = $v;
			$this->modifiedColumns[] = RslResultPeer::CLASS_DESCRIPTION;
		}

		return $this;
	} // setClassDescription()

	/**
	 * Set the value of [meta_sintesys] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setMetaSintesys($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->meta_sintesys !== $v) {
			$this->meta_sintesys = $v;
			$this->modifiedColumns[] = RslResultPeer::META_SINTESYS;
		}

		return $this;
	} // setMetaSintesys()

	/**
	 * Set the value of [results] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setResults($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->results !== $v) {
			$this->results = $v;
			$this->modifiedColumns[] = RslResultPeer::RESULTS;
		}

		return $this;
	} // setResults()

	/**
	 * Set the value of [discussions] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setDiscussions($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->discussions !== $v) {
			$this->discussions = $v;
			$this->modifiedColumns[] = RslResultPeer::DISCUSSIONS;
		}

		return $this;
	} // setDiscussions()

	/**
	 * Set the value of [conclusions] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setConclusions($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->conclusions !== $v) {
			$this->conclusions = $v;
			$this->modifiedColumns[] = RslResultPeer::CONCLUSIONS;
		}

		return $this;
	} // setConclusions()

	/**
	 * Set the value of [practice_implications] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setPracticeImplications($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->practice_implications !== $v) {
			$this->practice_implications = $v;
			$this->modifiedColumns[] = RslResultPeer::PRACTICE_IMPLICATIONS;
		}

		return $this;
	} // setPracticeImplications()

	/**
	 * Set the value of [search_implications] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setSearchImplications($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->search_implications !== $v) {
			$this->search_implications = $v;
			$this->modifiedColumns[] = RslResultPeer::SEARCH_IMPLICATIONS;
		}

		return $this;
	} // setSearchImplications()

	/**
	 * Set the value of [appointments] column.
	 * 
	 * @param      string $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setAppointments($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->appointments !== $v) {
			$this->appointments = $v;
			$this->modifiedColumns[] = RslResultPeer::APPOINTMENTS;
		}

		return $this;
	} // setAppointments()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = RslResultPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = RslResultPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = RslResultPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [created_by] column.
	 * 
	 * @param      int $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setCreatedBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->created_by !== $v) {
			$this->created_by = $v;
			$this->modifiedColumns[] = RslResultPeer::CREATED_BY;
		}

		if ($this->asfGuardUserRelatedByCreatedBy !== null && $this->asfGuardUserRelatedByCreatedBy->getId() !== $v) {
			$this->asfGuardUserRelatedByCreatedBy = null;
		}

		return $this;
	} // setCreatedBy()

	/**
	 * Set the value of [updated_by] column.
	 * 
	 * @param      int $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setUpdatedBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->updated_by !== $v) {
			$this->updated_by = $v;
			$this->modifiedColumns[] = RslResultPeer::UPDATED_BY;
		}

		if ($this->asfGuardUserRelatedByUpdatedBy !== null && $this->asfGuardUserRelatedByUpdatedBy->getId() !== $v) {
			$this->asfGuardUserRelatedByUpdatedBy = null;
		}

		return $this;
	} // setUpdatedBy()

	/**
	 * Set the value of [deleted_by] column.
	 * 
	 * @param      int $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setDeletedBy($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->deleted_by !== $v) {
			$this->deleted_by = $v;
			$this->modifiedColumns[] = RslResultPeer::DELETED_BY;
		}

		if ($this->asfGuardUserRelatedByDeletedBy !== null && $this->asfGuardUserRelatedByDeletedBy->getId() !== $v) {
			$this->asfGuardUserRelatedByDeletedBy = null;
		}

		return $this;
	} // setDeletedBy()

	/**
	 * Set the value of [rsl_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RslResult The current object (for fluent API support)
	 */
	public function setRslId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rsl_id !== $v) {
			$this->rsl_id = $v;
			$this->modifiedColumns[] = RslResultPeer::RSL_ID;
		}

		if ($this->aSystematicReview !== null && $this->aSystematicReview->getId() !== $v) {
			$this->aSystematicReview = null;
		}

		return $this;
	} // setRslId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->data_sintesys = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->class_description = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->meta_sintesys = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->results = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->discussions = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->conclusions = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->practice_implications = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->search_implications = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->appointments = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->created_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->updated_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->deleted_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->created_by = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->updated_by = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->deleted_by = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->rsl_id = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = RslResultPeer::NUM_COLUMNS - RslResultPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RslResult object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUserRelatedByCreatedBy !== null && $this->created_by !== $this->asfGuardUserRelatedByCreatedBy->getId()) {
			$this->asfGuardUserRelatedByCreatedBy = null;
		}
		if ($this->asfGuardUserRelatedByUpdatedBy !== null && $this->updated_by !== $this->asfGuardUserRelatedByUpdatedBy->getId()) {
			$this->asfGuardUserRelatedByUpdatedBy = null;
		}
		if ($this->asfGuardUserRelatedByDeletedBy !== null && $this->deleted_by !== $this->asfGuardUserRelatedByDeletedBy->getId()) {
			$this->asfGuardUserRelatedByDeletedBy = null;
		}
		if ($this->aSystematicReview !== null && $this->rsl_id !== $this->aSystematicReview->getId()) {
			$this->aSystematicReview = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RslResultPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RslResultPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUserRelatedByCreatedBy = null;
			$this->asfGuardUserRelatedByUpdatedBy = null;
			$this->asfGuardUserRelatedByDeletedBy = null;
			$this->aSystematicReview = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RslResultPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRslResult:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				RslResultPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRslResult:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RslResultPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseRslResult:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(RslResultPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(RslResultPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseRslResult:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				RslResultPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUserRelatedByCreatedBy !== null) {
				if ($this->asfGuardUserRelatedByCreatedBy->isModified() || $this->asfGuardUserRelatedByCreatedBy->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByCreatedBy->save($con);
				}
				$this->setsfGuardUserRelatedByCreatedBy($this->asfGuardUserRelatedByCreatedBy);
			}

			if ($this->asfGuardUserRelatedByUpdatedBy !== null) {
				if ($this->asfGuardUserRelatedByUpdatedBy->isModified() || $this->asfGuardUserRelatedByUpdatedBy->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByUpdatedBy->save($con);
				}
				$this->setsfGuardUserRelatedByUpdatedBy($this->asfGuardUserRelatedByUpdatedBy);
			}

			if ($this->asfGuardUserRelatedByDeletedBy !== null) {
				if ($this->asfGuardUserRelatedByDeletedBy->isModified() || $this->asfGuardUserRelatedByDeletedBy->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByDeletedBy->save($con);
				}
				$this->setsfGuardUserRelatedByDeletedBy($this->asfGuardUserRelatedByDeletedBy);
			}

			if ($this->aSystematicReview !== null) {
				if ($this->aSystematicReview->isModified() || $this->aSystematicReview->isNew()) {
					$affectedRows += $this->aSystematicReview->save($con);
				}
				$this->setSystematicReview($this->aSystematicReview);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RslResultPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RslResultPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RslResultPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUserRelatedByCreatedBy !== null) {
				if (!$this->asfGuardUserRelatedByCreatedBy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByCreatedBy->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByUpdatedBy !== null) {
				if (!$this->asfGuardUserRelatedByUpdatedBy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByUpdatedBy->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByDeletedBy !== null) {
				if (!$this->asfGuardUserRelatedByDeletedBy->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByDeletedBy->getValidationFailures());
				}
			}

			if ($this->aSystematicReview !== null) {
				if (!$this->aSystematicReview->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSystematicReview->getValidationFailures());
				}
			}


			if (($retval = RslResultPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RslResultPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getDataSintesys();
				break;
			case 2:
				return $this->getClassDescription();
				break;
			case 3:
				return $this->getMetaSintesys();
				break;
			case 4:
				return $this->getResults();
				break;
			case 5:
				return $this->getDiscussions();
				break;
			case 6:
				return $this->getConclusions();
				break;
			case 7:
				return $this->getPracticeImplications();
				break;
			case 8:
				return $this->getSearchImplications();
				break;
			case 9:
				return $this->getAppointments();
				break;
			case 10:
				return $this->getCreatedAt();
				break;
			case 11:
				return $this->getUpdatedAt();
				break;
			case 12:
				return $this->getDeletedAt();
				break;
			case 13:
				return $this->getCreatedBy();
				break;
			case 14:
				return $this->getUpdatedBy();
				break;
			case 15:
				return $this->getDeletedBy();
				break;
			case 16:
				return $this->getRslId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RslResultPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getDataSintesys(),
			$keys[2] => $this->getClassDescription(),
			$keys[3] => $this->getMetaSintesys(),
			$keys[4] => $this->getResults(),
			$keys[5] => $this->getDiscussions(),
			$keys[6] => $this->getConclusions(),
			$keys[7] => $this->getPracticeImplications(),
			$keys[8] => $this->getSearchImplications(),
			$keys[9] => $this->getAppointments(),
			$keys[10] => $this->getCreatedAt(),
			$keys[11] => $this->getUpdatedAt(),
			$keys[12] => $this->getDeletedAt(),
			$keys[13] => $this->getCreatedBy(),
			$keys[14] => $this->getUpdatedBy(),
			$keys[15] => $this->getDeletedBy(),
			$keys[16] => $this->getRslId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RslResultPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setDataSintesys($value);
				break;
			case 2:
				$this->setClassDescription($value);
				break;
			case 3:
				$this->setMetaSintesys($value);
				break;
			case 4:
				$this->setResults($value);
				break;
			case 5:
				$this->setDiscussions($value);
				break;
			case 6:
				$this->setConclusions($value);
				break;
			case 7:
				$this->setPracticeImplications($value);
				break;
			case 8:
				$this->setSearchImplications($value);
				break;
			case 9:
				$this->setAppointments($value);
				break;
			case 10:
				$this->setCreatedAt($value);
				break;
			case 11:
				$this->setUpdatedAt($value);
				break;
			case 12:
				$this->setDeletedAt($value);
				break;
			case 13:
				$this->setCreatedBy($value);
				break;
			case 14:
				$this->setUpdatedBy($value);
				break;
			case 15:
				$this->setDeletedBy($value);
				break;
			case 16:
				$this->setRslId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RslResultPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDataSintesys($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setClassDescription($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setMetaSintesys($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setResults($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDiscussions($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setConclusions($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPracticeImplications($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setSearchImplications($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setAppointments($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setCreatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUpdatedAt($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDeletedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedBy($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedBy($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDeletedBy($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setRslId($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RslResultPeer::DATABASE_NAME);

		if ($this->isColumnModified(RslResultPeer::ID)) $criteria->add(RslResultPeer::ID, $this->id);
		if ($this->isColumnModified(RslResultPeer::DATA_SINTESYS)) $criteria->add(RslResultPeer::DATA_SINTESYS, $this->data_sintesys);
		if ($this->isColumnModified(RslResultPeer::CLASS_DESCRIPTION)) $criteria->add(RslResultPeer::CLASS_DESCRIPTION, $this->class_description);
		if ($this->isColumnModified(RslResultPeer::META_SINTESYS)) $criteria->add(RslResultPeer::META_SINTESYS, $this->meta_sintesys);
		if ($this->isColumnModified(RslResultPeer::RESULTS)) $criteria->add(RslResultPeer::RESULTS, $this->results);
		if ($this->isColumnModified(RslResultPeer::DISCUSSIONS)) $criteria->add(RslResultPeer::DISCUSSIONS, $this->discussions);
		if ($this->isColumnModified(RslResultPeer::CONCLUSIONS)) $criteria->add(RslResultPeer::CONCLUSIONS, $this->conclusions);
		if ($this->isColumnModified(RslResultPeer::PRACTICE_IMPLICATIONS)) $criteria->add(RslResultPeer::PRACTICE_IMPLICATIONS, $this->practice_implications);
		if ($this->isColumnModified(RslResultPeer::SEARCH_IMPLICATIONS)) $criteria->add(RslResultPeer::SEARCH_IMPLICATIONS, $this->search_implications);
		if ($this->isColumnModified(RslResultPeer::APPOINTMENTS)) $criteria->add(RslResultPeer::APPOINTMENTS, $this->appointments);
		if ($this->isColumnModified(RslResultPeer::CREATED_AT)) $criteria->add(RslResultPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(RslResultPeer::UPDATED_AT)) $criteria->add(RslResultPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(RslResultPeer::DELETED_AT)) $criteria->add(RslResultPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(RslResultPeer::CREATED_BY)) $criteria->add(RslResultPeer::CREATED_BY, $this->created_by);
		if ($this->isColumnModified(RslResultPeer::UPDATED_BY)) $criteria->add(RslResultPeer::UPDATED_BY, $this->updated_by);
		if ($this->isColumnModified(RslResultPeer::DELETED_BY)) $criteria->add(RslResultPeer::DELETED_BY, $this->deleted_by);
		if ($this->isColumnModified(RslResultPeer::RSL_ID)) $criteria->add(RslResultPeer::RSL_ID, $this->rsl_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RslResultPeer::DATABASE_NAME);

		$criteria->add(RslResultPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RslResult (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDataSintesys($this->data_sintesys);

		$copyObj->setClassDescription($this->class_description);

		$copyObj->setMetaSintesys($this->meta_sintesys);

		$copyObj->setResults($this->results);

		$copyObj->setDiscussions($this->discussions);

		$copyObj->setConclusions($this->conclusions);

		$copyObj->setPracticeImplications($this->practice_implications);

		$copyObj->setSearchImplications($this->search_implications);

		$copyObj->setAppointments($this->appointments);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setDeletedAt($this->deleted_at);

		$copyObj->setCreatedBy($this->created_by);

		$copyObj->setUpdatedBy($this->updated_by);

		$copyObj->setDeletedBy($this->deleted_by);

		$copyObj->setRslId($this->rsl_id);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RslResult Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RslResultPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RslResultPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     RslResult The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByCreatedBy(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setCreatedBy(NULL);
		} else {
			$this->setCreatedBy($v->getId());
		}

		$this->asfGuardUserRelatedByCreatedBy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addRslResultRelatedByCreatedBy($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByCreatedBy(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByCreatedBy === null && ($this->created_by !== null)) {
			$this->asfGuardUserRelatedByCreatedBy = sfGuardUserPeer::retrieveByPk($this->created_by);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByCreatedBy->addRslResultsRelatedByCreatedBy($this);
			 */
		}
		return $this->asfGuardUserRelatedByCreatedBy;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     RslResult The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByUpdatedBy(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUpdatedBy(NULL);
		} else {
			$this->setUpdatedBy($v->getId());
		}

		$this->asfGuardUserRelatedByUpdatedBy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addRslResultRelatedByUpdatedBy($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByUpdatedBy(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByUpdatedBy === null && ($this->updated_by !== null)) {
			$this->asfGuardUserRelatedByUpdatedBy = sfGuardUserPeer::retrieveByPk($this->updated_by);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByUpdatedBy->addRslResultsRelatedByUpdatedBy($this);
			 */
		}
		return $this->asfGuardUserRelatedByUpdatedBy;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     RslResult The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByDeletedBy(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setDeletedBy(NULL);
		} else {
			$this->setDeletedBy($v->getId());
		}

		$this->asfGuardUserRelatedByDeletedBy = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addRslResultRelatedByDeletedBy($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByDeletedBy(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByDeletedBy === null && ($this->deleted_by !== null)) {
			$this->asfGuardUserRelatedByDeletedBy = sfGuardUserPeer::retrieveByPk($this->deleted_by);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByDeletedBy->addRslResultsRelatedByDeletedBy($this);
			 */
		}
		return $this->asfGuardUserRelatedByDeletedBy;
	}

	/**
	 * Declares an association between this object and a SystematicReview object.
	 *
	 * @param      SystematicReview $v
	 * @return     RslResult The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSystematicReview(SystematicReview $v = null)
	{
		if ($v === null) {
			$this->setRslId(NULL);
		} else {
			$this->setRslId($v->getId());
		}

		$this->aSystematicReview = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SystematicReview object, it will not be re-added.
		if ($v !== null) {
			$v->addRslResult($this);
		}

		return $this;
	}


	/**
	 * Get the associated SystematicReview object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SystematicReview The associated SystematicReview object.
	 * @throws     PropelException
	 */
	public function getSystematicReview(PropelPDO $con = null)
	{
		if ($this->aSystematicReview === null && ($this->rsl_id !== null)) {
			$this->aSystematicReview = SystematicReviewPeer::retrieveByPk($this->rsl_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSystematicReview->addRslResults($this);
			 */
		}
		return $this->aSystematicReview;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->asfGuardUserRelatedByCreatedBy = null;
			$this->asfGuardUserRelatedByUpdatedBy = null;
			$this->asfGuardUserRelatedByDeletedBy = null;
			$this->aSystematicReview = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseRslResult:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseRslResult::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseRslResult

// symfony_behaviors behavior
include_once 'lib/model/om/BaseRslResultBehaviors.php';
