<?php

/**
 * Base class that represents a row from the 'protocols' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Aug 22 18:28:57 2013
 *
 * @package    lib.model.om
 */
abstract class BaseProtocol extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ProtocolPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the objective field.
	 * @var        string
	 */
	protected $objective;

	/**
	 * The value for the population field.
	 * @var        string
	 */
	protected $population;

	/**
	 * The value for the intervention field.
	 * @var        string
	 */
	protected $intervention;

	/**
	 * The value for the comparative field.
	 * @var        string
	 */
	protected $comparative;

	/**
	 * The value for the outcome field.
	 * @var        string
	 */
	protected $outcome;

	/**
	 * The value for the context field.
	 * @var        string
	 */
	protected $context;

	/**
	 * The value for the search_string field.
	 * @var        string
	 */
	protected $search_string;

	/**
	 * The value for the metodology field.
	 * @var        string
	 */
	protected $metodology;

	/**
	 * The value for the assessment field.
	 * @var        string
	 */
	protected $assessment;

	/**
	 * The value for the data_extraction field.
	 * @var        string
	 */
	protected $data_extraction;

	/**
	 * The value for the data_analisys field.
	 * @var        string
	 */
	protected $data_analisys;

	/**
	 * The value for the dissemination field.
	 * @var        string
	 */
	protected $dissemination;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the deleted_at field.
	 * @var        string
	 */
	protected $deleted_at;

	/**
	 * The value for the rsl_id field.
	 * @var        int
	 */
	protected $rsl_id;

	/**
	 * The value for the framework_id field.
	 * @var        int
	 */
	protected $framework_id;

	/**
	 * The value for the strategy_id field.
	 * @var        int
	 */
	protected $strategy_id;

	/**
	 * @var        SystematicReview
	 */
	protected $aSystematicReview;

	/**
	 * @var        Framework
	 */
	protected $aFramework;

	/**
	 * @var        array SystematicReviewSearchBase[] Collection to store aggregation of SystematicReviewSearchBase objects.
	 */
	protected $collSystematicReviewSearchBases;

	/**
	 * @var        Criteria The criteria used to select the current contents of collSystematicReviewSearchBases.
	 */
	private $lastSystematicReviewSearchBaseCriteria = null;

	/**
	 * @var        array Job[] Collection to store aggregation of Job objects.
	 */
	protected $collJobs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collJobs.
	 */
	private $lastJobCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ProtocolPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [objective] column value.
	 * 
	 * @return     string
	 */
	public function getObjective()
	{
		return $this->objective;
	}

	/**
	 * Get the [population] column value.
	 * 
	 * @return     string
	 */
	public function getPopulation()
	{
		return $this->population;
	}

	/**
	 * Get the [intervention] column value.
	 * 
	 * @return     string
	 */
	public function getIntervention()
	{
		return $this->intervention;
	}

	/**
	 * Get the [comparative] column value.
	 * 
	 * @return     string
	 */
	public function getComparative()
	{
		return $this->comparative;
	}

	/**
	 * Get the [outcome] column value.
	 * 
	 * @return     string
	 */
	public function getOutcome()
	{
		return $this->outcome;
	}

	/**
	 * Get the [context] column value.
	 * 
	 * @return     string
	 */
	public function getContext()
	{
		return $this->context;
	}

	/**
	 * Get the [search_string] column value.
	 * 
	 * @return     string
	 */
	public function getSearchString()
	{
		return $this->search_string;
	}

	/**
	 * Get the [metodology] column value.
	 * 
	 * @return     string
	 */
	public function getMetodology()
	{
		return $this->metodology;
	}

	/**
	 * Get the [assessment] column value.
	 * 
	 * @return     string
	 */
	public function getAssessment()
	{
		return $this->assessment;
	}

	/**
	 * Get the [data_extraction] column value.
	 * 
	 * @return     string
	 */
	public function getDataExtraction()
	{
		return $this->data_extraction;
	}

	/**
	 * Get the [data_analisys] column value.
	 * 
	 * @return     string
	 */
	public function getDataAnalisys()
	{
		return $this->data_analisys;
	}

	/**
	 * Get the [dissemination] column value.
	 * 
	 * @return     string
	 */
	public function getDissemination()
	{
		return $this->dissemination;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [deleted_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDeletedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->deleted_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->deleted_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->deleted_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [rsl_id] column value.
	 * 
	 * @return     int
	 */
	public function getRslId()
	{
		return $this->rsl_id;
	}

	/**
	 * Get the [framework_id] column value.
	 * 
	 * @return     int
	 */
	public function getFrameworkId()
	{
		return $this->framework_id;
	}

	/**
	 * Get the [strategy_id] column value.
	 * 
	 * @return     int
	 */
	public function getStrategyId()
	{
		return $this->strategy_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ProtocolPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [objective] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setObjective($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->objective !== $v) {
			$this->objective = $v;
			$this->modifiedColumns[] = ProtocolPeer::OBJECTIVE;
		}

		return $this;
	} // setObjective()

	/**
	 * Set the value of [population] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setPopulation($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->population !== $v) {
			$this->population = $v;
			$this->modifiedColumns[] = ProtocolPeer::POPULATION;
		}

		return $this;
	} // setPopulation()

	/**
	 * Set the value of [intervention] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setIntervention($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->intervention !== $v) {
			$this->intervention = $v;
			$this->modifiedColumns[] = ProtocolPeer::INTERVENTION;
		}

		return $this;
	} // setIntervention()

	/**
	 * Set the value of [comparative] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setComparative($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comparative !== $v) {
			$this->comparative = $v;
			$this->modifiedColumns[] = ProtocolPeer::COMPARATIVE;
		}

		return $this;
	} // setComparative()

	/**
	 * Set the value of [outcome] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setOutcome($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->outcome !== $v) {
			$this->outcome = $v;
			$this->modifiedColumns[] = ProtocolPeer::OUTCOME;
		}

		return $this;
	} // setOutcome()

	/**
	 * Set the value of [context] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setContext($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->context !== $v) {
			$this->context = $v;
			$this->modifiedColumns[] = ProtocolPeer::CONTEXT;
		}

		return $this;
	} // setContext()

	/**
	 * Set the value of [search_string] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setSearchString($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->search_string !== $v) {
			$this->search_string = $v;
			$this->modifiedColumns[] = ProtocolPeer::SEARCH_STRING;
		}

		return $this;
	} // setSearchString()

	/**
	 * Set the value of [metodology] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setMetodology($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->metodology !== $v) {
			$this->metodology = $v;
			$this->modifiedColumns[] = ProtocolPeer::METODOLOGY;
		}

		return $this;
	} // setMetodology()

	/**
	 * Set the value of [assessment] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setAssessment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->assessment !== $v) {
			$this->assessment = $v;
			$this->modifiedColumns[] = ProtocolPeer::ASSESSMENT;
		}

		return $this;
	} // setAssessment()

	/**
	 * Set the value of [data_extraction] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setDataExtraction($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->data_extraction !== $v) {
			$this->data_extraction = $v;
			$this->modifiedColumns[] = ProtocolPeer::DATA_EXTRACTION;
		}

		return $this;
	} // setDataExtraction()

	/**
	 * Set the value of [data_analisys] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setDataAnalisys($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->data_analisys !== $v) {
			$this->data_analisys = $v;
			$this->modifiedColumns[] = ProtocolPeer::DATA_ANALISYS;
		}

		return $this;
	} // setDataAnalisys()

	/**
	 * Set the value of [dissemination] column.
	 * 
	 * @param      string $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setDissemination($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dissemination !== $v) {
			$this->dissemination = $v;
			$this->modifiedColumns[] = ProtocolPeer::DISSEMINATION;
		}

		return $this;
	} // setDissemination()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = ProtocolPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = ProtocolPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [deleted_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setDeletedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->deleted_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->deleted_at !== null && $tmpDt = new DateTime($this->deleted_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->deleted_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = ProtocolPeer::DELETED_AT;
			}
		} // if either are not null

		return $this;
	} // setDeletedAt()

	/**
	 * Set the value of [rsl_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setRslId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->rsl_id !== $v) {
			$this->rsl_id = $v;
			$this->modifiedColumns[] = ProtocolPeer::RSL_ID;
		}

		if ($this->aSystematicReview !== null && $this->aSystematicReview->getId() !== $v) {
			$this->aSystematicReview = null;
		}

		return $this;
	} // setRslId()

	/**
	 * Set the value of [framework_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setFrameworkId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->framework_id !== $v) {
			$this->framework_id = $v;
			$this->modifiedColumns[] = ProtocolPeer::FRAMEWORK_ID;
		}

		if ($this->aFramework !== null && $this->aFramework->getId() !== $v) {
			$this->aFramework = null;
		}

		return $this;
	} // setFrameworkId()

	/**
	 * Set the value of [strategy_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Protocol The current object (for fluent API support)
	 */
	public function setStrategyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->strategy_id !== $v) {
			$this->strategy_id = $v;
			$this->modifiedColumns[] = ProtocolPeer::STRATEGY_ID;
		}

		return $this;
	} // setStrategyId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->objective = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->population = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->intervention = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->comparative = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->outcome = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->context = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->search_string = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->metodology = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->assessment = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->data_extraction = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->data_analisys = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->dissemination = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->created_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->updated_at = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->deleted_at = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->rsl_id = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->framework_id = ($row[$startcol + 17] !== null) ? (int) $row[$startcol + 17] : null;
			$this->strategy_id = ($row[$startcol + 18] !== null) ? (int) $row[$startcol + 18] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 19; // 19 = ProtocolPeer::NUM_COLUMNS - ProtocolPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Protocol object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aSystematicReview !== null && $this->rsl_id !== $this->aSystematicReview->getId()) {
			$this->aSystematicReview = null;
		}
		if ($this->aFramework !== null && $this->framework_id !== $this->aFramework->getId()) {
			$this->aFramework = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProtocolPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ProtocolPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aSystematicReview = null;
			$this->aFramework = null;
			$this->collSystematicReviewSearchBases = null;
			$this->lastSystematicReviewSearchBaseCriteria = null;

			$this->collJobs = null;
			$this->lastJobCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProtocolPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseProtocol:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				ProtocolPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseProtocol:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ProtocolPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseProtocol:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			if ($this->isModified() && !$this->isColumnModified(ProtocolPeer::UPDATED_AT))
			{
			  $this->setUpdatedAt(time());
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(ProtocolPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseProtocol:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				ProtocolPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSystematicReview !== null) {
				if ($this->aSystematicReview->isModified() || $this->aSystematicReview->isNew()) {
					$affectedRows += $this->aSystematicReview->save($con);
				}
				$this->setSystematicReview($this->aSystematicReview);
			}

			if ($this->aFramework !== null) {
				if ($this->aFramework->isModified() || $this->aFramework->isNew()) {
					$affectedRows += $this->aFramework->save($con);
				}
				$this->setFramework($this->aFramework);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ProtocolPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ProtocolPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ProtocolPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collSystematicReviewSearchBases !== null) {
				foreach ($this->collSystematicReviewSearchBases as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collJobs !== null) {
				foreach ($this->collJobs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aSystematicReview !== null) {
				if (!$this->aSystematicReview->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aSystematicReview->getValidationFailures());
				}
			}

			if ($this->aFramework !== null) {
				if (!$this->aFramework->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFramework->getValidationFailures());
				}
			}


			if (($retval = ProtocolPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collSystematicReviewSearchBases !== null) {
					foreach ($this->collSystematicReviewSearchBases as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collJobs !== null) {
					foreach ($this->collJobs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProtocolPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getObjective();
				break;
			case 2:
				return $this->getPopulation();
				break;
			case 3:
				return $this->getIntervention();
				break;
			case 4:
				return $this->getComparative();
				break;
			case 5:
				return $this->getOutcome();
				break;
			case 6:
				return $this->getContext();
				break;
			case 7:
				return $this->getSearchString();
				break;
			case 8:
				return $this->getMetodology();
				break;
			case 9:
				return $this->getAssessment();
				break;
			case 10:
				return $this->getDataExtraction();
				break;
			case 11:
				return $this->getDataAnalisys();
				break;
			case 12:
				return $this->getDissemination();
				break;
			case 13:
				return $this->getCreatedAt();
				break;
			case 14:
				return $this->getUpdatedAt();
				break;
			case 15:
				return $this->getDeletedAt();
				break;
			case 16:
				return $this->getRslId();
				break;
			case 17:
				return $this->getFrameworkId();
				break;
			case 18:
				return $this->getStrategyId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ProtocolPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getObjective(),
			$keys[2] => $this->getPopulation(),
			$keys[3] => $this->getIntervention(),
			$keys[4] => $this->getComparative(),
			$keys[5] => $this->getOutcome(),
			$keys[6] => $this->getContext(),
			$keys[7] => $this->getSearchString(),
			$keys[8] => $this->getMetodology(),
			$keys[9] => $this->getAssessment(),
			$keys[10] => $this->getDataExtraction(),
			$keys[11] => $this->getDataAnalisys(),
			$keys[12] => $this->getDissemination(),
			$keys[13] => $this->getCreatedAt(),
			$keys[14] => $this->getUpdatedAt(),
			$keys[15] => $this->getDeletedAt(),
			$keys[16] => $this->getRslId(),
			$keys[17] => $this->getFrameworkId(),
			$keys[18] => $this->getStrategyId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ProtocolPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setObjective($value);
				break;
			case 2:
				$this->setPopulation($value);
				break;
			case 3:
				$this->setIntervention($value);
				break;
			case 4:
				$this->setComparative($value);
				break;
			case 5:
				$this->setOutcome($value);
				break;
			case 6:
				$this->setContext($value);
				break;
			case 7:
				$this->setSearchString($value);
				break;
			case 8:
				$this->setMetodology($value);
				break;
			case 9:
				$this->setAssessment($value);
				break;
			case 10:
				$this->setDataExtraction($value);
				break;
			case 11:
				$this->setDataAnalisys($value);
				break;
			case 12:
				$this->setDissemination($value);
				break;
			case 13:
				$this->setCreatedAt($value);
				break;
			case 14:
				$this->setUpdatedAt($value);
				break;
			case 15:
				$this->setDeletedAt($value);
				break;
			case 16:
				$this->setRslId($value);
				break;
			case 17:
				$this->setFrameworkId($value);
				break;
			case 18:
				$this->setStrategyId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ProtocolPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setObjective($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPopulation($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIntervention($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setComparative($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setOutcome($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setContext($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setSearchString($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setMetodology($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setAssessment($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDataExtraction($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDataAnalisys($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDissemination($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCreatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setUpdatedAt($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setDeletedAt($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setRslId($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setFrameworkId($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setStrategyId($arr[$keys[18]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);

		if ($this->isColumnModified(ProtocolPeer::ID)) $criteria->add(ProtocolPeer::ID, $this->id);
		if ($this->isColumnModified(ProtocolPeer::OBJECTIVE)) $criteria->add(ProtocolPeer::OBJECTIVE, $this->objective);
		if ($this->isColumnModified(ProtocolPeer::POPULATION)) $criteria->add(ProtocolPeer::POPULATION, $this->population);
		if ($this->isColumnModified(ProtocolPeer::INTERVENTION)) $criteria->add(ProtocolPeer::INTERVENTION, $this->intervention);
		if ($this->isColumnModified(ProtocolPeer::COMPARATIVE)) $criteria->add(ProtocolPeer::COMPARATIVE, $this->comparative);
		if ($this->isColumnModified(ProtocolPeer::OUTCOME)) $criteria->add(ProtocolPeer::OUTCOME, $this->outcome);
		if ($this->isColumnModified(ProtocolPeer::CONTEXT)) $criteria->add(ProtocolPeer::CONTEXT, $this->context);
		if ($this->isColumnModified(ProtocolPeer::SEARCH_STRING)) $criteria->add(ProtocolPeer::SEARCH_STRING, $this->search_string);
		if ($this->isColumnModified(ProtocolPeer::METODOLOGY)) $criteria->add(ProtocolPeer::METODOLOGY, $this->metodology);
		if ($this->isColumnModified(ProtocolPeer::ASSESSMENT)) $criteria->add(ProtocolPeer::ASSESSMENT, $this->assessment);
		if ($this->isColumnModified(ProtocolPeer::DATA_EXTRACTION)) $criteria->add(ProtocolPeer::DATA_EXTRACTION, $this->data_extraction);
		if ($this->isColumnModified(ProtocolPeer::DATA_ANALISYS)) $criteria->add(ProtocolPeer::DATA_ANALISYS, $this->data_analisys);
		if ($this->isColumnModified(ProtocolPeer::DISSEMINATION)) $criteria->add(ProtocolPeer::DISSEMINATION, $this->dissemination);
		if ($this->isColumnModified(ProtocolPeer::CREATED_AT)) $criteria->add(ProtocolPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(ProtocolPeer::UPDATED_AT)) $criteria->add(ProtocolPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(ProtocolPeer::DELETED_AT)) $criteria->add(ProtocolPeer::DELETED_AT, $this->deleted_at);
		if ($this->isColumnModified(ProtocolPeer::RSL_ID)) $criteria->add(ProtocolPeer::RSL_ID, $this->rsl_id);
		if ($this->isColumnModified(ProtocolPeer::FRAMEWORK_ID)) $criteria->add(ProtocolPeer::FRAMEWORK_ID, $this->framework_id);
		if ($this->isColumnModified(ProtocolPeer::STRATEGY_ID)) $criteria->add(ProtocolPeer::STRATEGY_ID, $this->strategy_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);

		$criteria->add(ProtocolPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Protocol (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setObjective($this->objective);

		$copyObj->setPopulation($this->population);

		$copyObj->setIntervention($this->intervention);

		$copyObj->setComparative($this->comparative);

		$copyObj->setOutcome($this->outcome);

		$copyObj->setContext($this->context);

		$copyObj->setSearchString($this->search_string);

		$copyObj->setMetodology($this->metodology);

		$copyObj->setAssessment($this->assessment);

		$copyObj->setDataExtraction($this->data_extraction);

		$copyObj->setDataAnalisys($this->data_analisys);

		$copyObj->setDissemination($this->dissemination);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setDeletedAt($this->deleted_at);

		$copyObj->setRslId($this->rsl_id);

		$copyObj->setFrameworkId($this->framework_id);

		$copyObj->setStrategyId($this->strategy_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getSystematicReviewSearchBases() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addSystematicReviewSearchBase($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getJobs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addJob($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Protocol Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ProtocolPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ProtocolPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a SystematicReview object.
	 *
	 * @param      SystematicReview $v
	 * @return     Protocol The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setSystematicReview(SystematicReview $v = null)
	{
		if ($v === null) {
			$this->setRslId(NULL);
		} else {
			$this->setRslId($v->getId());
		}

		$this->aSystematicReview = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the SystematicReview object, it will not be re-added.
		if ($v !== null) {
			$v->addProtocol($this);
		}

		return $this;
	}


	/**
	 * Get the associated SystematicReview object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     SystematicReview The associated SystematicReview object.
	 * @throws     PropelException
	 */
	public function getSystematicReview(PropelPDO $con = null)
	{
		if ($this->aSystematicReview === null && ($this->rsl_id !== null)) {
			$this->aSystematicReview = SystematicReviewPeer::retrieveByPk($this->rsl_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aSystematicReview->addProtocols($this);
			 */
		}
		return $this->aSystematicReview;
	}

	/**
	 * Declares an association between this object and a Framework object.
	 *
	 * @param      Framework $v
	 * @return     Protocol The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFramework(Framework $v = null)
	{
		if ($v === null) {
			$this->setFrameworkId(NULL);
		} else {
			$this->setFrameworkId($v->getId());
		}

		$this->aFramework = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Framework object, it will not be re-added.
		if ($v !== null) {
			$v->addProtocol($this);
		}

		return $this;
	}


	/**
	 * Get the associated Framework object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Framework The associated Framework object.
	 * @throws     PropelException
	 */
	public function getFramework(PropelPDO $con = null)
	{
		if ($this->aFramework === null && ($this->framework_id !== null)) {
			$this->aFramework = FrameworkPeer::retrieveByPk($this->framework_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFramework->addProtocols($this);
			 */
		}
		return $this->aFramework;
	}

	/**
	 * Clears out the collSystematicReviewSearchBases collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addSystematicReviewSearchBases()
	 */
	public function clearSystematicReviewSearchBases()
	{
		$this->collSystematicReviewSearchBases = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collSystematicReviewSearchBases collection (array).
	 *
	 * By default this just sets the collSystematicReviewSearchBases collection to an empty array (like clearcollSystematicReviewSearchBases());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initSystematicReviewSearchBases()
	{
		$this->collSystematicReviewSearchBases = array();
	}

	/**
	 * Gets an array of SystematicReviewSearchBase objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Protocol has previously been saved, it will retrieve
	 * related SystematicReviewSearchBases from storage. If this Protocol is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array SystematicReviewSearchBase[]
	 * @throws     PropelException
	 */
	public function getSystematicReviewSearchBases($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSystematicReviewSearchBases === null) {
			if ($this->isNew()) {
			   $this->collSystematicReviewSearchBases = array();
			} else {

				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				SystematicReviewSearchBasePeer::addSelectColumns($criteria);
				$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				SystematicReviewSearchBasePeer::addSelectColumns($criteria);
				if (!isset($this->lastSystematicReviewSearchBaseCriteria) || !$this->lastSystematicReviewSearchBaseCriteria->equals($criteria)) {
					$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastSystematicReviewSearchBaseCriteria = $criteria;
		return $this->collSystematicReviewSearchBases;
	}

	/**
	 * Returns the number of related SystematicReviewSearchBase objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related SystematicReviewSearchBase objects.
	 * @throws     PropelException
	 */
	public function countSystematicReviewSearchBases(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collSystematicReviewSearchBases === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				$count = SystematicReviewSearchBasePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				if (!isset($this->lastSystematicReviewSearchBaseCriteria) || !$this->lastSystematicReviewSearchBaseCriteria->equals($criteria)) {
					$count = SystematicReviewSearchBasePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collSystematicReviewSearchBases);
				}
			} else {
				$count = count($this->collSystematicReviewSearchBases);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a SystematicReviewSearchBase object to this object
	 * through the SystematicReviewSearchBase foreign key attribute.
	 *
	 * @param      SystematicReviewSearchBase $l SystematicReviewSearchBase
	 * @return     void
	 * @throws     PropelException
	 */
	public function addSystematicReviewSearchBase(SystematicReviewSearchBase $l)
	{
		if ($this->collSystematicReviewSearchBases === null) {
			$this->initSystematicReviewSearchBases();
		}
		if (!in_array($l, $this->collSystematicReviewSearchBases, true)) { // only add it if the **same** object is not already associated
			array_push($this->collSystematicReviewSearchBases, $l);
			$l->setProtocol($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Protocol is new, it will return
	 * an empty collection; or if this Protocol has previously
	 * been saved, it will retrieve related SystematicReviewSearchBases from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Protocol.
	 */
	public function getSystematicReviewSearchBasesJoinSystematicReview($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSystematicReviewSearchBases === null) {
			if ($this->isNew()) {
				$this->collSystematicReviewSearchBases = array();
			} else {

				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelectJoinSystematicReview($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

			if (!isset($this->lastSystematicReviewSearchBaseCriteria) || !$this->lastSystematicReviewSearchBaseCriteria->equals($criteria)) {
				$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelectJoinSystematicReview($criteria, $con, $join_behavior);
			}
		}
		$this->lastSystematicReviewSearchBaseCriteria = $criteria;

		return $this->collSystematicReviewSearchBases;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Protocol is new, it will return
	 * an empty collection; or if this Protocol has previously
	 * been saved, it will retrieve related SystematicReviewSearchBases from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Protocol.
	 */
	public function getSystematicReviewSearchBasesJoinSearchBase($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collSystematicReviewSearchBases === null) {
			if ($this->isNew()) {
				$this->collSystematicReviewSearchBases = array();
			} else {

				$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

				$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelectJoinSearchBase($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(SystematicReviewSearchBasePeer::PROTOCOL_ID, $this->id);

			if (!isset($this->lastSystematicReviewSearchBaseCriteria) || !$this->lastSystematicReviewSearchBaseCriteria->equals($criteria)) {
				$this->collSystematicReviewSearchBases = SystematicReviewSearchBasePeer::doSelectJoinSearchBase($criteria, $con, $join_behavior);
			}
		}
		$this->lastSystematicReviewSearchBaseCriteria = $criteria;

		return $this->collSystematicReviewSearchBases;
	}

	/**
	 * Clears out the collJobs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addJobs()
	 */
	public function clearJobs()
	{
		$this->collJobs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collJobs collection (array).
	 *
	 * By default this just sets the collJobs collection to an empty array (like clearcollJobs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initJobs()
	{
		$this->collJobs = array();
	}

	/**
	 * Gets an array of Job objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Protocol has previously been saved, it will retrieve
	 * related Jobs from storage. If this Protocol is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Job[]
	 * @throws     PropelException
	 */
	public function getJobs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
			   $this->collJobs = array();
			} else {

				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				JobPeer::addSelectColumns($criteria);
				$this->collJobs = JobPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				JobPeer::addSelectColumns($criteria);
				if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
					$this->collJobs = JobPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastJobCriteria = $criteria;
		return $this->collJobs;
	}

	/**
	 * Returns the number of related Job objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Job objects.
	 * @throws     PropelException
	 */
	public function countJobs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				$count = JobPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
					$count = JobPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collJobs);
				}
			} else {
				$count = count($this->collJobs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Job object to this object
	 * through the Job foreign key attribute.
	 *
	 * @param      Job $l Job
	 * @return     void
	 * @throws     PropelException
	 */
	public function addJob(Job $l)
	{
		if ($this->collJobs === null) {
			$this->initJobs();
		}
		if (!in_array($l, $this->collJobs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collJobs, $l);
			$l->setProtocol($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Protocol is new, it will return
	 * an empty collection; or if this Protocol has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Protocol.
	 */
	public function getJobsJoinActivity($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinActivity($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Protocol is new, it will return
	 * an empty collection; or if this Protocol has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Protocol.
	 */
	public function getJobsJoinsfGuardUserRelatedByUserId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByUserId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByUserId($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Protocol is new, it will return
	 * an empty collection; or if this Protocol has previously
	 * been saved, it will retrieve related Jobs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Protocol.
	 */
	public function getJobsJoinsfGuardUserRelatedByFinishedBy($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ProtocolPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collJobs === null) {
			if ($this->isNew()) {
				$this->collJobs = array();
			} else {

				$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByFinishedBy($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(JobPeer::PROTOCOL_ID, $this->id);

			if (!isset($this->lastJobCriteria) || !$this->lastJobCriteria->equals($criteria)) {
				$this->collJobs = JobPeer::doSelectJoinsfGuardUserRelatedByFinishedBy($criteria, $con, $join_behavior);
			}
		}
		$this->lastJobCriteria = $criteria;

		return $this->collJobs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collSystematicReviewSearchBases) {
				foreach ((array) $this->collSystematicReviewSearchBases as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collJobs) {
				foreach ((array) $this->collJobs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collSystematicReviewSearchBases = null;
		$this->collJobs = null;
			$this->aSystematicReview = null;
			$this->aFramework = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseProtocol:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseProtocol::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseProtocol

// symfony_behaviors behavior
include_once 'lib/model/om/BaseProtocolBehaviors.php';
