<?php


/**
 * Skeleton subclass for performing query and update operations on the 'access_tokens' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun  4 23:20:24 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AccessTokenPeer extends BaseAccessTokenPeer {

} // AccessTokenPeer
