<?php


/**
 * Skeleton subclass for representing a row from the 'activities' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Apr  2 10:11:37 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Activity extends BaseActivity {


	public function getChildren()
	{

		$c = new Criteria();
		$c->add(ActivityPeer::ACTIVITY_PARENT, $this->getId());
		$c->addAscendingOrderByColumn(ActivityPeer::ID);
		$children = ActivityPeer::doSelect($c);

		if($children)
		{
			return $children;
		}
		else
		{
			return null;
		}
	}

	public function getCachedJobs()
	{
	  return $this->collJobs;
	}

	public function getJob($protocol_id = null)
	{
		$c = new Criteria();
		$c->add(JobPeer::ACTIVITY_ID, $this->getId());
		$c->add(JobPeer::PROTOCOL_ID, $protocol_id);
		return $job = JobPeer::doSelectOne($c);
	}

} // Activity
