<?php


/**
 * Skeleton subclass for representing a row from the 'data_extractions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Apr 12 17:42:54 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DataExtraction extends BaseDataExtraction {

} // DataExtraction
