<?php


/**
 * Skeleton subclass for performing query and update operations on the 'frameworks' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  3 19:03:33 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FrameworkPeer extends BaseFrameworkPeer {
  const FRAMEWORK_KITCHENHAM = 1;
  const FRAMEWORK_BIOLCHINI = 2;
} // FrameworkPeer
