<?php


/**
 * Skeleton subclass for performing query and update operations on the 'metadata' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb 22 19:41:46 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MetadataPeer extends BaseMetadataPeer {

  public static function doSelectList(Criteria $c)
  {
    $c = clone $c;
    $c->clearSelectColumns()
      ->addSelectColumn(self::ID)
      ->addSelectColumn(self::NAME)
      ->addSelectColumn(self::DESCRIPTION)
      ->addSelectColumn(self::TYPE);
      
    
    return self::doSelectRS($c);
  }	
	
  
  public static function doSelectRS(Criteria $criteria, $con = null)
  {

    foreach (sfMixer::getCallables('BaseMetadataPeer:doSelectRS:doSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseMetadataPeer', $criteria, $con);
    }



    foreach (sfMixer::getCallables('BaseMetadataPeer:addDoSelectRS:addDoSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseMetadataPeer', $criteria, $con);
    }


    if ($con === null) {
      $con = Propel::getConnection(self::DATABASE_NAME);
    }

    if (!$criteria->getSelectColumns()) {
      $criteria = clone $criteria;
      MetadataPeer::addSelectColumns($criteria);
    }

        $criteria->setDbName(self::DATABASE_NAME);

            return BasePeer::doSelect($criteria, $con);
  }  
} // MetadataPeer

