<?php


/**
 * Skeleton subclass for representing a row from the 'observacoes' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Apr 21 15:51:09 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Observacao extends BaseObservacao {
  const STATUS_FINISHED = 1;
} // Observacao
