<?php


/**
 * Skeleton subclass for performing query and update operations on the 'onthologies' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jul 26 18:53:36 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class OnthologyPeer extends BaseOnthologyPeer {

} // OnthologyPeer
