<?php


/**
 * Skeleton subclass for performing query and update operations on the 'questions' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Nov 14 15:15:05 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class QuestionPeer extends BaseQuestionPeer {
	public static function doSelectForForm(Criteria $c)
	{
		$c = clone $c;
		$c->clearSelectColumns()
			->addSelectColumn(self::ID)//0
			->addSelectColumn(self::DESCRIPTION)//1
			->addSelectColumn(self::ANSWER_TYPE)//2
			->addSelectColumn(AnswerPeer::QUESTION_ID)//3
			->addSelectColumn(AnswerPeer::ANSWER)//4
			->addSelectColumn(AnswerPeer::UPDATED_AT)//5
		;
		
		return self::doSelectRs($c);
	}
  public static function doSelectRS(Criteria $criteria, $con = null)
  {
  
    foreach (sfMixer::getCallables('BaseQuestionPeer:doSelectRS:doSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseQuestionPeer', $criteria, $con);
    }
  
  
  
    foreach (sfMixer::getCallables('BaseQuestionPeer:addDoSelectRS:addDoSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseQuestionPeer', $criteria, $con);
    }
  
  
    if ($con === null) {
      $con = Propel::getConnection(self::DATABASE_NAME);
    }
  
    if (!$criteria->getSelectColumns()) {
      $criteria = clone $criteria;
      QuestionPeer::addSelectColumns($criteria);
    }
  
    $criteria->setDbName(self::DATABASE_NAME);
  
    return BasePeer::doSelect($criteria, $con);
  }
} // QuestionPeer
