<?php


/**
 * Skeleton subclass for performing query and update operations on the 'rsl_criterias' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Jan  7 09:06:45 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class RslCriteriaPeer extends BaseRslCriteriaPeer {
	public static function doSelectForSelection(Criteria $c)
	{
		$c = clone $c;
		$c->clearSelectColumns()
		->addSelectColumn(self::ID)
		->addSelectColumn(self::NAME)
		->addSelectColumn(self::TYPE);
	
		$c->addDescendingOrderByColumn(self::TYPE);
		return self::doSelectRS($c);
	}
  
  public static function doSelectRS(Criteria $criteria, $con = null)
  {
  
    foreach (sfMixer::getCallables('BaseRslCriteriaPeer:doSelectRS:doSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseRslCriteriaPeer', $criteria, $con);
    }
  
  
  
    foreach (sfMixer::getCallables('BaseRslCriteriaPeer:addDoSelectRS:addDoSelectRS') as $callable)
    {
      call_user_func($callable, 'BaseRslCriteriaPeer', $criteria, $con);
    }
  
  
    if ($con === null) {
      $con = Propel::getConnection(self::DATABASE_NAME);
    }
  
    if (!$criteria->getSelectColumns()) {
      $criteria = clone $criteria;
      RslCriteriaPeer::addSelectColumns($criteria);
    }
  
    $criteria->setDbName(self::DATABASE_NAME);
  
    return BasePeer::doSelect($criteria, $con);
  }

} // RslCriteriaPeer
