<?php


/**
 * Skeleton subclass for representing a row from the 'systematic_reviews' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Oct 20 13:59:37 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SystematicReview extends BaseSystematicReview {
  const COORDENADOR = 0;
  public function __toString(){
    echo $this->getTitle();
  }
  
} // SystematicReview
sfPropelBehavior::add('SystematicReview', array ('paranoid' => array ('column' => 'deleted_at')));
sfPropelBehavior::add('ForumPost', array (
    'sfPropelActAsSignableBehavior' => array (
      'columns' => array (
        'created' => SystematicReviewPeer::CREATED_BY,
        'updated' => SystematicReviewPeer::UPDATED_BY,
        'deleted' => SystematicReviewPeer::DELETED_BY
      )
    )
  )
);
