<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/14 21:00:15

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:dbname=mestrado;host=localhost',
  'username' => 'postgres',
  'password' => '_r8cUz+t',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
