<?php
// auto-generated by sfSecurityConfigHandler
// date: 2016/09/14 21:00:16
$this->security = array (
  'about' => 
  array (
    'is_secure' => false,
  ),
  'contacts' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
