<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/02/11 18:40:31
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => true,
  ),
  'signout' => 
  array (
    'is_secure' => true,
  ),
  'join' => 
  array (
    'is_secure' => false,
  ),
  'confirm' => 
  array (
    'is_secure' => false,
  ),
  'createuser' => 
  array (
    'is_secure' => false,
  ),
  'retrievenewtoken' => 
  array (
    'is_secure' => false,
  ),
  'negate' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
