<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/02/11 18:40:31
$this->security = array (
  'about' => 
  array (
    'is_secure' => false,
  ),
  'contacts' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
