<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/05/19 09:42:27
sfConfig::add(array(
  'mod_systematic_review_enabled' => true,
  'mod_systematic_review_view_class' => 'sfPHP',
));
